python main.py \
    --ignore_search summary \
    --augment rand \
    --batch_size 48 \
    --epochs 700 \
    --optimizer adam \
    --lr 0.01 \
    --lr_mode cosine \
    --lr_warmup 5 \
    --loss supcon \
    --standardize norm \
    --data_path /workspace/data2/Dataset/cub/ \
    --gpus 0,1,2,3
